### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by DingGGu** [brandly/angular-adaptive-backgrounds#5]
i've got error some specific images.

`Uncaught TypeError: Cannot read property '0' of null`

source:
```html
<div adaptive-background>
   <img ng-src="{{data.data.cover == '0' && '/images/cover.jpg' || '/res/cover/'  + data.data.key + '.jpg'}}" width="300" />
</div>
```

image:
![image](http://utaitebox.ggu.la/res/cover/dRa8uO8z84.jpg)

**Comment by brandly** [comment]
i saved that photo to my computer and tried testing it locally. i don't see any error!

what line was that error thrown on?

**Comment by DingGGu** [comment]
I Solved it.
thanks
